build:
  controller:
    replicaCount: 1
    image:
      # use custom image until upstream PR merged https://github.com/knative/build/pull/519
      #repository: gcr.io/knative-releases/github.com/knative/build/cmd/controller@sha256
      repository: rawlingsj/build-controller
      tag: upstream3
    imagePullPolicy: IfNotPresent
    terminationGracePeriodSeconds: 30
    args:
    - -logtostderr
    - -stderrthreshold
    - INFO
    - -creds-image
    - registry.cn-beijing.aliyuncs.com/yunheli/creds-init:latest
    - -git-image
    - registry.cn-beijing.aliyuncs.com/yunheli/git-init:latest
    - -nop-image
    - registry.cn-beijing.aliyuncs.com/yunheli/nop:latest
    resources:
      limits:
      cpu: 200m
      memory: 256Mi
      requests:
      cpu: 100m
      memory: 128Mi
    service:
      type: ClusterIP
      externalPort: 9090
      internalPort: 9090
  auth:
    git:
      username:
      password:
      # username: my-bot
      # password: my-bot-token
image:
  creds: registry.cn-beijing.aliyuncs.com/yunheli/creds-init:latest
  git: registry.cn-beijing.aliyuncs.com/yunheli/git-init:latest
  gcs: registry.cn-beijing.aliyuncs.com/yunheli/gcs-fetcher:latest
  nop: registry.cn-beijing.aliyuncs.com/yunheli/nop:latest
